// French, Dutch, German, Spanish, Italian, Portuguese, Polish, Turkish, English.
export const networkRows=[
['Mon réseau','Mijn netwerk','Mein Netzwerk','Mi red','La mia rete','A minha rede','Moja sieć','Ağım','My network'],
['Connexions','Connecties','Kontakte','Contactos','Collegamenti','Conexões','Kontakty','Bağlantılar','Connections'],
['Suivis','Volgend','Gefolgt','Siguiendo','Seguiti','A seguir','Obserwowani','Takip edilenler','Following'],
['Mes connexions','Mijn connecties','Meine Kontakte','Mis contactos','I miei collegamenti','As minhas conexões','Moje kontakty','Bağlantılarım','My connections'],
['Profils suivis','Gevolgde profielen','Gefolgte Profile','Perfiles seguidos','Profili seguiti','Perfis seguidos','Obserwowane profile','Takip edilen profiller','Followed profiles'],
['Retour aux membres','Terug naar leden','Zurück zu Mitgliedern','Volver a miembros','Torna ai membri','Voltar aos membros','Powrót do członków','Üyelere dön','Back to members'],
['Rechercher dans cette liste…','Zoeken in deze lijst…','In dieser Liste suchen…','Buscar en esta lista…','Cerca in questo elenco…','Pesquisar nesta lista…','Szukaj na tej liście…','Bu listede ara…','Search this list…'],
['Connexion acceptée','Connectie geaccepteerd','Kontakt bestätigt','Conexión aceptada','Collegamento accettato','Conexão aceite','Zaakceptowany kontakt','Bağlantı kabul edildi','Connection accepted'],
['Vos connexions acceptées : échangez et invitez-les à jouer.','Je geaccepteerde connecties: praat met hen en nodig ze uit om te spelen.','Deine bestätigten Kontakte: Tauscht euch aus und ladet euch zum Spielen ein.','Tus contactos aceptados: conversa e invítalos a jugar.','I tuoi collegamenti accettati: parla con loro e invitali a giocare.','As tuas conexões aceites: conversa e convida-as para jogar.','Twoje zaakceptowane kontakty: rozmawiaj i zapraszaj do gry.','Kabul edilen bağlantıların: sohbet et ve maça davet et.','Your accepted connections: chat and invite them to play.'],
['Les membres dont vous suivez les publications. Suivre ne crée pas une connexion.','Leden van wie je berichten volgt. Volgen maakt geen connectie.','Mitglieder, deren Beiträge du verfolgst. Folgen stellt keine Verbindung her.','Miembros cuyas publicaciones sigues. Seguir no crea una conexión.','Membri di cui segui i post. Seguire non crea un collegamento.','Membros cujas publicações segues. Seguir não cria uma conexão.','Członkowie, których posty obserwujesz. Obserwowanie nie tworzy kontaktu.','Gönderilerini takip ettiğin üyeler. Takip etmek bağlantı kurmaz.','Members whose posts you follow. Following does not create a connection.'],
['Aucun membre trouvé.','Geen leden gevonden.','Keine Mitglieder gefunden.','No se encontraron miembros.','Nessun membro trovato.','Nenhum membro encontrado.','Nie znaleziono członków.','Üye bulunamadı.','No members found.'],
['Aucune connexion acceptée pour le moment.','Nog geen geaccepteerde connecties.','Noch keine bestätigten Kontakte.','Aún no tienes contactos aceptados.','Nessun collegamento accettato al momento.','Ainda não tens conexões aceites.','Nie masz jeszcze zaakceptowanych kontaktów.','Henüz kabul edilmiş bağlantı yok.','No accepted connections yet.'],
['Vous ne suivez encore aucun membre.','Je volgt nog geen leden.','Du folgst noch keinen Mitgliedern.','Aún no sigues a ningún miembro.','Non segui ancora nessun membro.','Ainda não segues nenhum membro.','Nie obserwujesz jeszcze żadnych członków.','Henüz hiçbir üyeyi takip etmiyorsun.','You are not following any members yet.'],
['Découvrir des membres','Leden ontdekken','Mitglieder entdecken','Descubrir miembros','Scopri i membri','Descobrir membros','Odkryj członków','Üyeleri keşfet','Discover members'],
] as const;
